gui:
  theme:
    # Espresso-matched (warm neutral)
    activeBorderColor:
      - "#a5c261" # green
      - bold
    inactiveBorderColor:
      - "#777777" # gray
    searchingActiveBorderColor:
      - "#ffc66d" # yellow/orange
      - bold
    optionsTextColor:
      - "#6c99bb" # blue
    selectedLineBgColor:
      - "#393939" # bg highlight
    selectedRangeBgColor:
      - "#393939" # bg highlight
    highlightedLineBgColor:
      - "#474747" # bg lighter
    defaultFgColor:
      - "#ffffff" # white fg
    unstagedChangesColor:
      - "#d25252" # red
    commitHashColor:
      - "#b98eff" # purple
    branchColor:
      - "#a5c261" # green
    diff:
      addColor:
        - "#a5c261" # green
      removeColor:
        - "#d25252" # red
    commandLogColor:
      - "#6c99bb" # blue
    fileColor:
      - "#ffffff" # white fg
